# .github/workflows/mirror.yml
name: 'mirror'
on:
  schedule:
    - cron: '*/3 * * * *'
jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      - name: mirror
        id: mirror
        uses: n14s/github-mirror-action@v1
        with:
          origin: "https://${{secrets.GITHUB_TOKEN}}@github.com/n14s/blink-break.git"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
